live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xe77171"
index = 16

[[colors.indexed_colors]]
color = "0x5ebaa5"
index = 17

[[colors.indexed_colors]]
color = "0x88909f"
index = 18

[[colors.indexed_colors]]
color = "0xb7bec9"
index = 19

[[colors.indexed_colors]]
color = "0x73b3e7"
index = 20

[[colors.indexed_colors]]
color = "0xd390e7"
index = 21

[colors.bright]
black = "0x3e4249"
blue = "0x73b3e7"
cyan = "0x5ebaa5"
green = "0xa1bf78"
magenta = "0xd390e7"
red = "0xe77171"
white = "0x3e4249"
yellow = "0xdbb774"

[colors.cursor]
cursor = "0xb7bec9"
text = "0x262729"

[colors.normal]
black = "0x262729"
blue = "0x73b3e7"
cyan = "0x5ebaa5"
green = "0xa1bf78"
magenta = "0xd390e7"
red = "0xe77171"
white = "0xb7bec9"
yellow = "0xdbb774"

[colors.primary]
background = "0x262729"
foreground = "0xb7bec9"

[font]
size = 10.5

[font.bold_italic]
family = "Cascadia Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Liga SFMono Nerd Font"
style = "Italic"

[font.normal]
family = "Liga SFMono Nerd Font"
style = "semibold"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "command"

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
opacity = 0.8

[window.padding]
x = 2
y = 2
