[colors.primary]
background = '#fcf8ff'
foreground = '#1b1b21'

[colors.cursor]
text = '#fcf8ff'
cursor = '#1b1b21'

[colors.vi_mode_cursor]
text = '#fcf8ff'
cursor = '#5a5892'

[colors.search.matches]
foreground = '#e4e1ec'
background = '#7a5368'

[colors.search.focused_match]
foreground = '#e4e1ec'
background = '#5a5892'

[colors.footer_bar]
foreground = '#e4e1ec'
background = '#313036'

[colors.hints.start]
foreground = '#e4e1ec'
background = '#5e5c71'

[colors.hints.end]
foreground = '#e4e1ec'
background = '#5e5c71'

[colors.selection]
text = '#47464f'
background = '#e4e1ec'


[colors.normal]
black   = '#e4e1ec'
red     = '#ba1a1a'
green   = '#5a5892'
yellow  = '#5e5c71'
blue    = '#7a5368'
magenta = '#716da6'
cyan    = '#737187'
white   = '#1b1b21'


[colors.bright]
black   = '#787680'
red     = '#ba1a1a'
green   = '#5a5892'
yellow  = '#5e5c71'
blue    = '#7a5368'
magenta = '#716da6'
cyan    = '#737187'
white   = '#1b1b21'


[colors.dim]
black   = '#e4e1ec'
red     = '#ba1a1a'
green   = '#5a5892'
yellow  = '#5e5c71'
blue    = '#7a5368'
magenta = '#716da6'
cyan    = '#737187'
white   = '#1b1b21'
