[colors.primary]
background = '#f9faef'
foreground = '#1a1d16'

[colors.cursor]
text = '#f9faef'
cursor = '#1a1d16'

[colors.vi_mode_cursor]
text = '#f9faef'
cursor = '#49672e'

[colors.search.matches]
foreground = '#e0e4d6'
background = '#386664'

[colors.search.focused_match]
foreground = '#e0e4d6'
background = '#49672e'

[colors.footer_bar]
foreground = '#e0e4d6'
background = '#2e312a'

[colors.hints.start]
foreground = '#e0e4d6'
background = '#57624a'

[colors.hints.end]
foreground = '#e0e4d6'
background = '#57624a'

[colors.selection]
text = '#44483e'
background = '#e0e4d6'


[colors.normal]
black   = '#e0e4d6'
red     = '#ba1a1a'
green   = '#49672e'
yellow  = '#57624a'
blue    = '#386664'
magenta = '#5d7c3b'
cyan    = '#6b775d'
white   = '#1a1d16'


[colors.bright]
black   = '#74796d'
red     = '#ba1a1a'
green   = '#49672e'
yellow  = '#57624a'
blue    = '#386664'
magenta = '#5d7c3b'
cyan    = '#6b775d'
white   = '#1a1d16'


[colors.dim]
black   = '#e0e4d6'
red     = '#ba1a1a'
green   = '#49672e'
yellow  = '#57624a'
blue    = '#386664'
magenta = '#5d7c3b'
cyan    = '#6b775d'
white   = '#1a1d16'
