[colors.primary]
background = '#f4fbfa'
foreground = '#161d1c'

[colors.cursor]
text = '#f4fbfa'
cursor = '#161d1c'

[colors.vi_mode_cursor]
text = '#f4fbfa'
cursor = '#006a69'

[colors.search.matches]
foreground = '#dae5e3'
background = '#4b607c'

[colors.search.focused_match]
foreground = '#dae5e3'
background = '#006a69'

[colors.footer_bar]
foreground = '#dae5e3'
background = '#2b3231'

[colors.hints.start]
foreground = '#dae5e3'
background = '#4a6362'

[colors.hints.end]
foreground = '#dae5e3'
background = '#4a6362'

[colors.selection]
text = '#3f4948'
background = '#dae5e3'


[colors.normal]
black   = '#dae5e3'
red     = '#ba1a1a'
green   = '#006a69'
yellow  = '#4a6362'
blue    = '#4b607c'
magenta = '#247f7e'
cyan    = '#5f7878'
white   = '#161d1c'


[colors.bright]
black   = '#6f7978'
red     = '#ba1a1a'
green   = '#006a69'
yellow  = '#4a6362'
blue    = '#4b607c'
magenta = '#247f7e'
cyan    = '#5f7878'
white   = '#161d1c'


[colors.dim]
black   = '#dae5e3'
red     = '#ba1a1a'
green   = '#006a69'
yellow  = '#4a6362'
blue    = '#4b607c'
magenta = '#247f7e'
cyan    = '#5f7878'
white   = '#161d1c'
