.pragma library

var languages = {
    "fr": {name: "french", aliases: ["french", "français", "fr"]},
    "en": {name: "english", aliases: ["english", "anglais", "en"]},
    "es": {name: "spanish", aliases: ["spanish", "espagnol", "es"]},
    "de": {name: "german", aliases: ["german", "allemand", "de"]},
    "it": {name: "italian", aliases: ["italian", "italien", "it"]},
    "pt": {name: "portuguese", aliases: ["portuguese", "portugais", "pt"]},
    "ru": {name: "russian", aliases: ["russian", "russe", "ru"]},
    "ja": {name: "japanese", aliases: ["japanese", "japonais", "ja"]},
    "zh": {name: "chinese", aliases: ["chinese", "chinois", "zh"]},
    "ko": {name: "korean", aliases: ["korean", "coréen", "ko"]},
    "ar": {name: "arabic", aliases: ["arabic", "arabe", "ar"]},
    "hi": {name: "hindi", aliases: ["hindi", "hi"]},
    "nl": {name: "dutch", aliases: ["dutch", "néerlandais", "hollandais", "nl"]},
    "pl": {name: "polish", aliases: ["polish", "polonais", "pl"]},
    "sv": {name: "swedish", aliases: ["swedish", "suédois", "sv"]},
    "da": {name: "danish", aliases: ["danish", "danois", "da"]},
    "no": {name: "norwegian", aliases: ["norwegian", "norvégien", "no"]},
    "fi": {name: "finnish", aliases: ["finnish", "finnois", "fi"]},
    "cs": {name: "czech", aliases: ["czech", "tchèque", "cs"]},
    "hu": {name: "hungarian", aliases: ["hungarian", "hongrois", "hu"]},
    "ro": {name: "romanian", aliases: ["romanian", "roumain", "ro"]},
    "tr": {name: "turkish", aliases: ["turkish", "turc", "tr"]},
    "uk": {name: "ukrainian", aliases: ["ukrainian", "ukrainien", "uk"]},
    "vi": {name: "vietnamese", aliases: ["vietnamese", "vietnamien", "vi"]},
    "th": {name: "thai", aliases: ["thai", "thaï", "th"]},
    "id": {name: "indonesian", aliases: ["indonesian", "indonésien", "id"]},
    "el": {name: "greek", aliases: ["greek", "grec", "el"]},
    "he": {name: "hebrew", aliases: ["hebrew", "hébreu", "he"]},
    "bg": {name: "bulgarian", aliases: ["bulgarian", "bulgare", "bg"]},
    "hr": {name: "croatian", aliases: ["croatian", "croate", "hr"]},
    "sr": {name: "serbian", aliases: ["serbian", "serbe", "sr"]},
    "sk": {name: "slovak", aliases: ["slovak", "slovaque", "sk"]},
    "sl": {name: "slovenian", aliases: ["slovenian", "slovène", "sl"]},
    "et": {name: "estonian", aliases: ["estonian", "estonien", "et"]},
    "lv": {name: "latvian", aliases: ["latvian", "letton", "lv"]},
    "lt": {name: "lithuanian", aliases: ["lithuanian", "lituanien", "lt"]},
    "ca": {name: "catalan", aliases: ["catalan", "catalan", "ca"]},
    "is": {name: "icelandic", aliases: ["icelandic", "islandais", "is"]},
    "mt": {name: "maltese", aliases: ["maltese", "maltais", "mt"]},
    "bn": {name: "bengali", aliases: ["bengali", "bengali", "bn"]},
    "ur": {name: "urdu", aliases: ["urdu", "ourdou", "ur"]},
    "fa": {name: "persian", aliases: ["persian", "persan", "farsi", "fa"]},
    "sw": {name: "swahili", aliases: ["swahili", "swahili", "sw"]},
    "ms": {name: "malay", aliases: ["malay", "malais", "ms"]},
    "tl": {name: "filipino", aliases: ["filipino", "tagalog", "philippin", "tl"]},
    "af": {name: "afrikaans", aliases: ["afrikaans", "afrikaans", "af"]},
    "sq": {name: "albanian", aliases: ["albanian", "albanais", "sq"]},
    "az": {name: "azerbaijani", aliases: ["azerbaijani", "azerbaïdjanais", "az"]},
    "eu": {name: "basque", aliases: ["basque", "basque", "eu"]},
    "be": {name: "belarusian", aliases: ["belarusian", "biélorusse", "be"]},
    "bs": {name: "bosnian", aliases: ["bosnian", "bosniaque", "bs"]},
    "gl": {name: "galician", aliases: ["galician", "galicien", "gl"]},
    "ka": {name: "georgian", aliases: ["georgian", "géorgien", "ka"]},
    "gu": {name: "gujarati", aliases: ["gujarati", "gujarati", "gu"]},
    "ha": {name: "hausa", aliases: ["hausa", "haoussa", "ha"]},
    "iw": {name: "hebrew", aliases: ["hebrew", "hébreu", "iw"]},
    "hmn": {name: "hmong", aliases: ["hmong", "hmong", "hmn"]},
    "ig": {name: "igbo", aliases: ["igbo", "igbo", "ig"]},
    "ga": {name: "irish", aliases: ["irish", "irlandais", "ga"]},
    "jw": {name: "javanese", aliases: ["javanese", "javanais", "jw"]},
    "kk": {name: "kazakh", aliases: ["kazakh", "kazakh", "kk"]},
    "km": {name: "khmer", aliases: ["khmer", "khmer", "km"]},
    "rw": {name: "kinyarwanda", aliases: ["kinyarwanda", "kinyarwanda", "rw"]},
    "ky": {name: "kyrgyz", aliases: ["kyrgyz", "kirghiz", "ky"]},
    "lo": {name: "lao", aliases: ["lao", "lao", "lo"]},
    "lb": {name: "luxembourgish", aliases: ["luxembourgish", "luxembourgeois", "lb"]},
    "mk": {name: "macedonian", aliases: ["macedonian", "macédonien", "mk"]},
    "mg": {name: "malagasy", aliases: ["malagasy", "malgache", "mg"]},
    "ml": {name: "malayalam", aliases: ["malayalam", "malayalam", "ml"]},
    "mi": {name: "maori", aliases: ["maori", "maori", "mi"]},
    "mr": {name: "marathi", aliases: ["marathi", "marathi", "mr"]},
    "mn": {name: "mongolian", aliases: ["mongolian", "mongol", "mn"]},
    "my": {name: "myanmar", aliases: ["myanmar", "birman", "my"]},
    "ne": {name: "nepali", aliases: ["nepali", "népalais", "ne"]},
    "ny": {name: "chichewa", aliases: ["chichewa", "chichewa", "ny"]},
    "ps": {name: "pashto", aliases: ["pashto", "pachto", "ps"]},
    "pa": {name: "punjabi", aliases: ["punjabi", "pendjabi", "pa"]},
    "sm": {name: "samoan", aliases: ["samoan", "samoan", "sm"]},
    "gd": {name: "scots", aliases: ["scots", "écossais", "gd"]},
    "sn": {name: "shona", aliases: ["shona", "shona", "sn"]},
    "sd": {name: "sindhi", aliases: ["sindhi", "sindhi", "sd"]},
    "si": {name: "sinhala", aliases: ["sinhala", "cingalais", "si"]},
    "so": {name: "somali", aliases: ["somali", "somali", "so"]},
    "su": {name: "sundanese", aliases: ["sundanese", "soundanais", "su"]},
    "tg": {name: "tajik", aliases: ["tajik", "tadjik", "tg"]},
    "ta": {name: "tamil", aliases: ["tamil", "tamoul", "ta"]},
    "tt": {name: "tatar", aliases: ["tatar", "tatar", "tt"]},
    "te": {name: "telugu", aliases: ["telugu", "télougou", "te"]},
    "uz": {name: "uzbek", aliases: ["uzbek", "ouzbek", "uz"]},
    "cy": {name: "welsh", aliases: ["welsh", "gallois", "cy"]},
    "xh": {name: "xhosa", aliases: ["xhosa", "xhosa", "xh"]},
    "yi": {name: "yiddish", aliases: ["yiddish", "yiddish", "yi"]},
    "yo": {name: "yoruba", aliases: ["yoruba", "yoruba", "yo"]},
    "zu": {name: "zulu", aliases: ["zulu", "zoulou", "zu"]}
};

function getLanguageCode(input) {
    if (!input || input.trim() === "") return "";
    var lower = input.toLowerCase();
    for (var code in languages) {
        if (languages[code].aliases.indexOf(lower) !== -1) return code;
    }
    return lower;
}
