exec-once = kbuildsycoca6
exec-once = kdeconnectd
exec-once = dbus-update-activation-environment --systemd XDG_MENU_PREFIX

exec-once = wlsunset -l 39.9 -L 116.3 -t 5000 -T 6000

# Status bar :)
# exec-once=eww open bar
exec-once=waybar

#Notification
exec-once=swaync --config ~/.config/swaync/config.json
# Wallpaper
# exec-once=swaybg -o \* -i ~/.config/hypr/wallpapers/summer.png -m fill
exec-once = swww-daemon --format xrgb
exec-once = ~/.config/hypr/wallpapers/switch.sh
# For screen sharing
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# For keyboardkkk
exec-once=fcitx5 -D
# For lockscreen
exec-once=swayidle -w timeout 600 'swaylock-fancy'
# Start Page
exec-once=~/.config/hypr/scripts/startpage.sh

exec-once=/usr/lib/polkit-kde-authentication-agent-1

# 阿里云盘
exec-once=/bin/aliyundrive-webdav

exec-once=hyprpm enable hyprexpo

# Bluetooth
# exec-once=blueman-applet # Make sure you have installed blueman

exec-once=nm-applet

# Screen Sharing
exec-once=systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=~/.config/hypr/scripts/screensharing.sh
