# Float Necessary Windows
# windowrule = float,pavucontrol-qt
# windowrule = float,dolphin
windowrule = stayfocused,class:(Rofi)
windowrule = float,class:(Rofi)
windowrule = float,class:^()$,title:^(Picture in picture)$
windowrule = float,title:^(媒体查看器)$
windowrule = float,class:^(brave)$,title:^(Save File)$kk
windowrule = float,class:^(brave)$,title:^(Open File)$
windowrule = float,class:^(LibreWolf)$,title:^(Picture-in-Picture)$
windowrule = float,class:^(blueman-manager)$
windowrule = float,class:^(org.twosheds.iwgtk)$
windowrule = float,class:^(blueberry.py)$
windowrule = float,class:^(float)$
windowrule = float,class:^(mpv)$
windowrule = float,class:^(nm-connection-editor)
windowrule = float,title:float
windowrule = float,class:^(xdg-desktop-portal-gtk)$
windowrule = float,class:^(geeqie)$
windowrule = float,class:^(org.kde.ark)
windowrule = float,title:Translate
windowrule = float,title:bluetui
windowrule = float,title:^KDE Connect.*
windowrule = float,title:^正在解压缩文件.*
windowrule = float,title:^正在压缩.*
windowrule = float,class:com.alibabainc.dingtalk
windowrule = float,class:copyq
windowrule = float,class:dmenu
windowrule = size 500 600,class:copyq
windowrule = size 800 600,class:foot,title:float
windowrule = size 700 400,class:foot,title:Translate
windowrule = move onscreen cursor,class:copyq
windowrule = move onscreen cursor,title:bluetui
# windowrulev2 = move onscreen cursor 0 -150,class:com.alibabainc.dingtalk
windowrule = noanim,class:com.alibabainc.dingtalk
windowrule = noanim,class:swappy
windowrule = noblur,class:Code
# windowrulev2=float,class:qutebrowser
windowrule = noblur,xwayland:1,floating:1
windowrule = opacity 1,xwayland:1,floating:1


# Increase the opacity
# windowrule=opacity 0.92,dolphin
# windowrule=opacity 0.96,discord
# windowrule=opacity 0.9,VSCodium
# windowrule=opacity 0.88,obsidian
# windowrule=opacity 0.93,telegram
# windowrule=opacity 0.96,qutebrowser
# windowrule=opacity 0.8,title:Translate
# windowrule=noblur,title:Translate

# ^.*nvim.*$
# windowrule=tile,librewolf
# windowrule=tile,spotify
# windowrule=opacity 1,neovim

# workspace = 2,layoutopt:master
