# Float Necessary Windows
# windowrule = float on, plugin:hyprbars:nobar, match:class (pavucontrol-qt)
windowrule = float on, match:class (org.kde.dolphin)
windowrule = float on, match:class (hyprland-share-picker)
windowrule = stay_focused on, match:class (Rofi)
windowrule = float on, match:class (Rofi)
windowrule = float on, match:class ^()$, match:title ^(Picture in picture)$
windowrule = float on, match:title ^(媒体查看器)$
windowrule = float on, match:title ^(图片)$
windowrule = float on, match:class ^(brave)$, match:title ^(Save File)$
windowrule = float on, match:class ^(brave)$, match:title ^(Open File)$
windowrule = float on, match:class ^(LibreWolf)$, match:title ^(Picture-in-Picture)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(org.twosheds.iwgtk)$
windowrule = float on, match:class ^(blueberry.py)$
windowrule = float on, match:class ^(float)$
windowrule = float on, match:class ^(mpv)$
windowrule = float on, match:class ^(nm-connection-editor)
windowrule = float on, match:title float
windowrule = float on, match:class ^(xdg-desktop-portal-gtk)$
windowrule = float on, match:class ^(geeqie)$
windowrule = float on, match:class ^(org.kde.ark)
windowrule = float on, match:title Translate
windowrule = float on, match:title bluetui
# windowrule = float on, plugin:hyprbars:nobar, match:title Lark会议
# windowrule = float on, plugin:hyprbars:nobar, match:title ^KDE Connect.*
# windowrule = float on, plugin:hyprbars:nobar, match:title ^正在解压缩文件.*
# windowrule = float on, plugin:hyprbars:nobar, match:title ^正在压缩.*
# windowrule = float on, plugin:hyprbars:nobar, match:class com.alibabainc.dingtalk
windowrule = float on, match:class copyq
windowrule = float on, match:class dmenu

# Size Rules
windowrule = size 500 600, match:class copyq
windowrule = size 800 600, match:class foot, match:title float
windowrule = size 700 400, match:class foot, match:title Translate

# Move Rules
windowrule = move onscreen cursor, match:class copyq
windowrule = move onscreen cursor, match:title bluetui
windowrule = move onscreen cursor, match:class pavucontrol-qt

# Animation / Visual Tweaks
# windowrule = move onscreen cursor 0 -150, match:class com.alibabainc.dingtalk
windowrule = no_anim on, match:class com.alibabainc.dingtalk
windowrule = no_anim on, match:class swappy
windowrule = no_blur on, match:class Code
# windowrule = border on, match:class Code
# windowrule = no_titlebar on, match:class Code
# windowrule = float on, match:class qutebrowser
windowrule = no_blur on, match:xwayland 1, match:float 1
windowrule = opacity 1, match:xwayland 1, match:float 1

# Opacity Rules
windowrule = opacity 0.92, match:class (org.kde.dolphin)
# windowrule = opacity 0.96, match:class discord
# windowrule = opacity 0.9, match:class VSCodium
# windowrule = opacity 0.88, match:class obsidian
windowrule = opacity 0.93, match:class (telegram)
windowrule = opacity 0.96, match:class (org.qutebrowser.qutebrowser)
windowrule = opacity 0.94, match:class (firefox)
# windowrule = opacity 0.8, match:title Translate
windowrule = no_blur on, match:title Translate

# ^.*nvim.*$
# windowrule = tile on, match:class librewolf
# windowrule = tile on, match:class spotify
# windowrule = opacity 1, match:class neovim


# 禁止平铺窗口显示 titlebar
# windowrule = plugin:hyprbars:nobar, match:float 0
# windowrule = plugin:hyprbars:nobar, match:title ^(Lark会议)$

layerrule = blur on, match:namespace background
# layerrule = no_border on, match:namespace rofi
