color0 #e1e2ec
color1 #ba1a1a
color2 #475d92
color3 #575e71
color4 #725572
color5 #5e72a5
color6 #6d7286
color7 #1a1b20
color8 #757780
color9 #ba1a1a
color10 #475d92
color11 #575e71
color12 #725572
color13 #5e72a5
color14 #6d7286
color15 #1a1b20

cursor                #1a1b20
cursor_text_color     #faf8ff
background            #faf8ff
foreground            #1a1b20
selection_foreground  #44464f
selection_background  #e1e2ec
active_border_color   #475d92
inactive_border_color #e1e2ec
url_color             #475d92

active_tab_foreground   #ffffff
active_tab_background   #475d92
inactive_tab_foreground #44464f
inactive_tab_background #e1e2ec
cursor_trail_color      #44464f
