color0 #404659
color1 #ffb4ab
color2 #59d5f8
color3 #86d1ea
color4 #b2c5ff
color5 #59d5f8
color6 #86d1ea
color7 #e0e2ef
color8 #8a90a5
color9 #ffb4ab
color10 #59d5f8
color11 #86d1ea
color12 #b2c5ff
color13 #59d5f8
color14 #86d1ea
color15 #e0e2ef

cursor                #e0e2ef
cursor_text_color     #10131c
background            #10131c
foreground            #e0e2ef
selection_foreground  #c0c6dd
selection_background  #404659
active_border_color   #59d5f8
inactive_border_color #404659
url_color             #59d5f8

active_tab_foreground   #003642
active_tab_background   #59d5f8
inactive_tab_foreground #c0c6dd
inactive_tab_background #404659
cursor_trail_color      #c0c6dd
