color0 #f4ded4
color1 #ba1a1a
color2 #8d4e2a
color3 #765848
color4 #646032
color5 #a4633f
color6 #8f6b5a
color7 #221a15
color8 #85736b
color9 #ba1a1a
color10 #8d4e2a
color11 #765848
color12 #646032
color13 #a4633f
color14 #8f6b5a
color15 #221a15

cursor                #221a15
cursor_text_color     #fff8f6
background            #fff8f6
foreground            #221a15
selection_foreground  #52443d
selection_background  #f4ded4
active_border_color   #8d4e2a
inactive_border_color #f4ded4
url_color             #8d4e2a

active_tab_foreground   #ffffff
active_tab_background   #8d4e2a
inactive_tab_foreground #52443d
inactive_tab_background #f4ded4
cursor_trail_color      #52443d
