gui:
  theme:
    activeBorderColor:
      - "#81cfff"
      - bold
    inactiveBorderColor:
      - "#91cef5"
    searchingActiveBorderColor:
      - "#c3c0ff"
      - bold
    optionsTextColor:
      - "#c7c4dd"
    selectedLineBgColor:
      - "#c7c4dd"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#c7c4dd"
    cherryPickedCommitBgColor:
      - "#c3c0ff"
    markedBaseCommitFgColor:
      - "#c3c0ff"
    markedBaseCommitBgColor:
      - "#ffb4ab"
    unstagedChangesColor:
      - "#ffb4ab"
    defaultFgColor:
      - "#e4e0ef"
