gui:
  theme:
    activeBorderColor:
      - "#535a92"
      - bold
    inactiveBorderColor:
      - "#5b5d72"
    searchingActiveBorderColor:
      - "#77536c"
      - bold
    optionsTextColor:
      - "#46464f"
    selectedLineBgColor:
      - "#46464f"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#46464f"
    cherryPickedCommitBgColor:
      - "#77536c"
    markedBaseCommitFgColor:
      - "#77536c"
    markedBaseCommitBgColor:
      - "#ba1a1a"
    unstagedChangesColor:
      - "#ba1a1a"
    defaultFgColor:
      - "#1b1b21"
