gui:
  theme:
    activeBorderColor:
      - "#59d5f8"
      - bold
    inactiveBorderColor:
      - "#86d1ea"
    searchingActiveBorderColor:
      - "#b2c5ff"
      - bold
    optionsTextColor:
      - "#c0c6dd"
    selectedLineBgColor:
      - "#c0c6dd"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#c0c6dd"
    cherryPickedCommitBgColor:
      - "#b2c5ff"
    markedBaseCommitFgColor:
      - "#b2c5ff"
    markedBaseCommitBgColor:
      - "#ffb4ab"
    unstagedChangesColor:
      - "#ffb4ab"
    defaultFgColor:
      - "#e0e2ef"
